In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/C.csv",header = None)

In [ ]:
df

     0    1    2    3    4    5    6   ...   13   14   15   16   17   18   19
0     0  100  100    9    5  100  100  ...  100    2  100    8  100  100  100
1   100    0  100  100  100  100  100  ...  100  100  100  100    5    5    5
2     6  100    0  100  100    4  100  ...    1  100  100  100  100  100  100
3   100  100  100    0    8    1  100  ...  100  100    4  100    1  100  100
4   100  100  100  100    0  100  100  ...  100  100  100    4  100  100  100
5   100  100  100  100  100    0  100  ...  100  100    3  100    9    3  100
6   100    9  100  100  100  100    0  ...  100  100  100  100  100  100  100
7   100  100    6  100  100  100  100  ...  100  100  100  100  100  100    8
8   100    9  100  100  100  100  100  ...  100    8  100  100  100  100  100
9     2  100  100  100  100    9  100  ...  100  100  100  100  100  100  100
10  100  100  100    7  100  100  100  ...  100  100  100  100  100  100  100
11  100  100  100    0  100  100  100  ...  100  100    7  100  100  100  100
12  100  100  100  100    2  100  100  ...  100  100  100  100  100  100  100
13   10  100  100  100  100  100  100  ...    0  100  100  100  100  100  100
14  100  100  100  100  100  100  100  ...  100    0  100  100  100  100  100
15  100  100  100  100  100  100  100  ...  100  100    0  100  100    2  100
16  100  100  100  100    5    9  100  ...  100  100  100    0  100  100  100
17  100  100  100  100  100    1  100  ...  100  100  100  100    0  100  100
18    1  100  100  100  100  100  100  ...    7  100  100  100  100    0  100
19  100    7  100  100  100  100  100  ...  100  100  100    5  100  100    0

[20 rows x 20 columns]

In [ ]:
def dijkstra(G, start):
    """
    Implementation of dijkstra using adjacency matrix.
    This returns an array containing the length of the shortest path from the start node to each other node.
    It is only guaranteed to return correct results if there are no negative edges in the graph. Positive cycles are fine.
    This has a runtime of O(|V|^2) (|V| = number of Nodes), for a faster implementation see @see ../fast/Dijkstra.java (using adjacency lists)

    :param graph: an adjacency-matrix-representation of the graph where (x,y) is the weight of the edge or 0 if there is no edge.
    :param start: the node to start from.
    :return: an array containing the shortest distances from the given start node to each other node
    """

    print(G)
    # This contains the distances from the start node to all other nodes
    distances = [G.iloc[start,_] for _ in range(len(G))]
    print(distances)

    # This contains whether a node was already visited
    visited = [False for _ in range(len(G))]


    # The distance from the start node to itself is 0
    distances[start] = 0
    path = {v:[]for v in G}
    path[start] = [start]
    count = 0

    for i in G.index:
      for j in G.index:
        min_value = min(G[i][j],G[j][i])
        G[i][j] = min_value
        G[j][i] = min_value

    
    # While there are nodes left to visit...
    while True:
        # ... find the node with the currently shortest distance from the start node...
        shortest_distance = 999999999
        shortest_index = -1
 
        for i in range(len(G)):
            # ... by going through all nodes that haven't been visited yet
            
            if distances[i] < shortest_distance and not visited[i]:
                shortest_distance = distances[i]
                shortest_index = i
                #count = count +1
                print("Visiting node " + str(shortest_index) + " with current shortest distance " + str(shortest_distance))

        if shortest_index == -1:
            # There was no node not yet visited --> We are done
            return distances

      
        # ...then, for all neighboring nodes that haven't been visited yet....
        x = list(range(len(G)))
        x.pop(shortest_index)
        print("x - " , x)
        print("Shortest Index - " , shortest_index)
        for i in x:
            # ...if path over this edge is shorter ...Save this path as new shortest path.
            if distances[i] > distances[shortest_index] + G[i][shortest_index]:
              distances[i] = distances[shortest_index] + G[shortest_index][i]
              print("Updating distance of node " + str(i) + " to " + str(distances[i]))
              path[i] = path[shortest_index] + [i]
              
              
        
        # Lastly, we are finished with this node.
        
        visited[shortest_index] = True
        print("Visited nodes: " + str(visited))
        print("Currently lowest distances: " + str(distances))

In [ ]:
dijkstra(df,6)

     0    1    2    3    4    5    6   ...   13   14   15   16   17   18   19
0     0  100  100    9    5  100  100  ...  100    2  100    8  100  100  100
1   100    0  100  100  100  100  100  ...  100  100  100  100    5    5    5
2     6  100    0  100  100    4  100  ...    1  100  100  100  100  100  100
3   100  100  100    0    8    1  100  ...  100  100    4  100    1  100  100
4   100  100  100  100    0  100  100  ...  100  100  100    4  100  100  100
5   100  100  100  100  100    0  100  ...  100  100    3  100    9    3  100
6   100    9  100  100  100  100    0  ...  100  100  100  100  100  100  100
7   100  100    6  100  100  100  100  ...  100  100  100  100  100  100    8
8   100    9  100  100  100  100  100  ...  100    8  100  100  100  100  100
9     2  100  100  100  100    9  100  ...  100  100  100  100  100  100  100
10  100  100  100    7  100  100  100  ...  100  100  100  100  100  100  100
11  100  100  100    0  100  100  100  ...  100  100    7  100  100  100  100
12  100  100  100  100    2  100  100  ...  100  100  100  100  100  100  100
13   10  100  100  100  100  100  100  ...    0  100  100  100  100  100  100
14  100  100  100  100  100  100  100  ...  100    0  100  100  100  100  100
15  100  100  100  100  100  100  100  ...  100  100    0  100  100    2  100
16  100  100  100  100    5    9  100  ...  100  100  100    0  100  100  100
17  100  100  100  100  100    1  100  ...  100  100  100  100    0  100  100
18    1  100  100  100  100  100  100  ...    7  100  100  100  100    0  100
19  100    7  100  100  100  100  100  ...  100  100  100    5  100  100    0

[20 rows x 20 columns]
[100, 9, 100, 100, 100, 100, 0, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
Visiting node 0 with current shortest distance 100
Visiting node 1 with current shortest distance 9
Visiting node 6 with current shortest distance 0
x -  [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  6
Visited nodes: [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]
Currently lowest distances: [100, 9, 100, 100, 100, 100, 0, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
Visiting node 0 with current shortest distance 100
Visiting node 1 with current shortest distance 9
x -  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  1
Updating distance of node 8 to 18
Updating distance of node 11 to 13
Updating distance of node 12 to 17
Updating distance of node 17 to 14
Updating distance of node 18 to 14
Updating distance of node 19 to 14
Visited nodes: [False, True, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]
Currently lowest distances: [100, 9, 100, 100, 100, 100, 0, 100, 18, 100, 100, 13, 17, 100, 100, 100, 100, 14, 14, 14]
Visiting node 0 with current shortest distance 100
Visiting node 8 with current shortest distance 18
Visiting node 11 with current shortest distance 13
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  11
Updating distance of node 0 to 19
Updating distance of node 2 to 15
Updating distance of node 3 to 13
Updating distance of node 9 to 18
Updating distance of node 15 to 20
Visited nodes: [False, True, False, False, False, False, True, False, False, False, False, True, False, False, False, False, False, False, False, False]
Currently lowest distances: [19, 9, 15, 13, 100, 100, 0, 100, 18, 18, 100, 13, 17, 100, 100, 20, 100, 14, 14, 14]
Visiting node 0 with current shortest distance 19
Visiting node 2 with current shortest distance 15
Visiting node 3 with current shortest distance 13
x -  [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  3
Updating distance of node 4 to 21
Updating distance of node 5 to 14
Updating distance of node 10 to 20
Updating distance of node 15 to 17
Visited nodes: [False, True, False, True, False, False, True, False, False, False, False, True, False, False, False, False, False, False, False, False]
Currently lowest distances: [19, 9, 15, 13, 21, 14, 0, 100, 18, 18, 20, 13, 17, 100, 100, 17, 100, 14, 14, 14]
Visiting node 0 with current shortest distance 19
Visiting node 2 with current shortest distance 15
Visiting node 5 with current shortest distance 14
x -  [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  5
Updating distance of node 7 to 23
Updating distance of node 16 to 23
Visited nodes: [False, True, False, True, False, True, True, False, False, False, False, True, False, False, False, False, False, False, False, False]
Currently lowest distances: [19, 9, 15, 13, 21, 14, 0, 23, 18, 18, 20, 13, 17, 100, 100, 17, 23, 14, 14, 14]
Visiting node 0 with current shortest distance 19
Visiting node 2 with current shortest distance 15
Visiting node 17 with current shortest distance 14
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19]
Shortest Index -  17
Visited nodes: [False, True, False, True, False, True, True, False, False, False, False, True, False, False, False, False, False, True, False, False]
Currently lowest distances: [19, 9, 15, 13, 21, 14, 0, 23, 18, 18, 20, 13, 17, 100, 100, 17, 23, 14, 14, 14]
Visiting node 0 with current shortest distance 19
Visiting node 2 with current shortest distance 15
Visiting node 18 with current shortest distance 14
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19]
Shortest Index -  18
Updating distance of node 0 to 15
Updating distance of node 13 to 21
Updating distance of node 15 to 16
Visited nodes: [False, True, False, True, False, True, True, False, False, False, False, True, False, False, False, False, False, True, True, False]
Currently lowest distances: [15, 9, 15, 13, 21, 14, 0, 23, 18, 18, 20, 13, 17, 21, 100, 16, 23, 14, 14, 14]
Visiting node 0 with current shortest distance 15
Visiting node 19 with current shortest distance 14
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Shortest Index -  19
Updating distance of node 7 to 22
Updating distance of node 16 to 19
Visited nodes: [False, True, False, True, False, True, True, False, False, False, False, True, False, False, False, False, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 21, 14, 0, 22, 18, 18, 20, 13, 17, 21, 100, 16, 19, 14, 14, 14]
Visiting node 0 with current shortest distance 15
x -  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  0
Updating distance of node 4 to 20
Updating distance of node 9 to 17
Updating distance of node 14 to 17
Visited nodes: [True, True, False, True, False, True, True, False, False, False, False, True, False, False, False, False, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 20, 14, 0, 22, 18, 17, 20, 13, 17, 21, 17, 16, 19, 14, 14, 14]
Visiting node 2 with current shortest distance 15
x -  [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  2
Updating distance of node 7 to 21
Updating distance of node 13 to 16
Visited nodes: [True, True, True, True, False, True, True, False, False, False, False, True, False, False, False, False, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 20, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 20
Visiting node 8 with current shortest distance 18
Visiting node 9 with current shortest distance 17
Visiting node 13 with current shortest distance 16
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19]
Shortest Index -  13
Visited nodes: [True, True, True, True, False, True, True, False, False, False, False, True, False, True, False, False, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 20, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 20
Visiting node 8 with current shortest distance 18
Visiting node 9 with current shortest distance 17
Visiting node 15 with current shortest distance 16
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19]
Shortest Index -  15
Visited nodes: [True, True, True, True, False, True, True, False, False, False, False, True, False, True, False, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 20, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 20
Visiting node 8 with current shortest distance 18
Visiting node 9 with current shortest distance 17
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  9
Visited nodes: [True, True, True, True, False, True, True, False, False, True, False, True, False, True, False, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 20, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 20
Visiting node 8 with current shortest distance 18
Visiting node 12 with current shortest distance 17
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  12
Updating distance of node 4 to 19
Visited nodes: [True, True, True, True, False, True, True, False, False, True, False, True, True, True, False, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 19
Visiting node 8 with current shortest distance 18
Visiting node 14 with current shortest distance 17
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19]
Shortest Index -  14
Visited nodes: [True, True, True, True, False, True, True, False, False, True, False, True, True, True, True, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 19
Visiting node 8 with current shortest distance 18
x -  [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  8
Visited nodes: [True, True, True, True, False, True, True, False, True, True, False, True, True, True, True, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 4 with current shortest distance 19
x -  [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  4
Visited nodes: [True, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, False, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 7 with current shortest distance 21
Visiting node 10 with current shortest distance 20
Visiting node 16 with current shortest distance 19
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19]
Shortest Index -  16
Visited nodes: [True, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 7 with current shortest distance 21
Visiting node 10 with current shortest distance 20
x -  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  10
Visited nodes: [True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]
Visiting node 7 with current shortest distance 21
x -  [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Shortest Index -  7
Visited nodes: [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
Currently lowest distances: [15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]

[15, 9, 15, 13, 19, 14, 0, 21, 18, 17, 20, 13, 17, 16, 17, 16, 19, 14, 14, 14]

In [ ]:
df

     0    1    2    3    4    5    6   ...   13   14   15   16   17   18   19
0     0  100    6    9    5  100  100  ...   10    2  100    8  100    1  100
1   100    0  100  100  100  100    9  ...  100  100  100  100    5    5    5
2     6  100    0  100  100    4  100  ...    1  100  100  100  100  100  100
3     9  100  100    0    8    1  100  ...  100  100    4  100    1  100  100
4     5  100  100    8    0  100  100  ...  100  100  100    4  100  100  100
5   100  100    4    1  100    0  100  ...  100  100    3    9    1    3  100
6   100    9  100  100  100  100    0  ...  100  100  100  100  100  100  100
7   100  100    6  100  100    9  100  ...  100  100  100  100  100  100    8
8   100    9  100  100  100   10  100  ...  100    8  100  100    8  100  100
9     2  100  100  100  100    9  100  ...  100  100    6  100    6  100  100
10  100  100  100    7  100  100  100  ...  100  100  100  100  100  100  100
11    6    4    2    0  100  100  100  ...  100  100    7  100    1  100  100
12  100    8  100  100    2  100  100  ...  100  100    1  100  100  100  100
13   10  100    1  100  100  100  100  ...    0  100  100  100  100    7  100
14    2  100  100  100  100  100  100  ...  100    0  100  100  100  100  100
15  100  100  100    4  100    3  100  ...  100  100    0  100  100    2  100
16    8  100  100  100    4    9  100  ...  100  100  100    0  100  100    5
17  100    5  100    1  100    1  100  ...  100  100  100  100    0  100  100
18    1    5  100  100  100    3  100  ...    7  100    2  100  100    0  100
19  100    5  100  100  100  100  100  ...  100  100  100    5  100  100    0

[20 rows x 20 columns]

In [ ]:
# path from u (start) to v(target) with k edges
def shortestPath(graph, u, v, k):
    Inf = 99999999
    
    for i in graph.index:
      for j in graph.index:
        min_value = min(graph[i][j],graph[j][i])
        graph[i][j] = min_value
        graph[j][i] = min_value

# Base cases
    print("start node - ",u ,"final node" ,v ,"initial steps", k)
    if k == 0 and u == v:
        return 0
    if k == 1 and graph[u][v] != Inf:
        return graph[u][v]
    if k <= 0:
        return Inf
 
# Initializing
    res = Inf
 
# Go to all adjacents of u and recur
    for i in range(len(graph)):
        if graph[u][i] != Inf and u != i and v != i:
            rec_res = shortestPath(graph, i, v, k - 1)
            if rec_res != Inf:
                res = min(res, graph[u][i] + rec_res)
                print("least distance -",res)
    return res

In [ ]:
shortestPath(df,2,3,)

start node -  2 final node 3 initial steps 2
start node -  0 final node 3 initial steps 1
least distance - 15
start node -  1 final node 3 initial steps 1
least distance - 15
start node -  4 final node 3 initial steps 1
least distance - 15
start node -  5 final node 3 initial steps 1
least distance - 5
start node -  6 final node 3 initial steps 1
least distance - 5
start node -  7 final node 3 initial steps 1
least distance - 5
start node -  8 final node 3 initial steps 1
least distance - 5
start node -  9 final node 3 initial steps 1
least distance - 5
start node -  10 final node 3 initial steps 1
least distance - 5
start node -  11 final node 3 initial steps 1
least distance - 2
start node -  12 final node 3 initial steps 1
least distance - 2
start node -  13 final node 3 initial steps 1
least distance - 2
start node -  14 final node 3 initial steps 1
least distance - 2
start node -  15 final node 3 initial steps 1
least distance - 2
start node -  16 final node 3 initial steps 1
least distance - 2
start node -  17 final node 3 initial steps 1
least distance - 2
start node -  18 final node 3 initial steps 1
least distance - 2
start node -  19 final node 3 initial steps 1
least distance - 2

2